In [13]:
import pandas as pd
df = pd.read_csv('/content/Dataset .csv')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [15]:
 City_counts = df['City'].value_counts()
 most_Restaurants_City = City_counts.idxmax()
 print(most_Restaurants_City)

New Delhi

In [23]:
City_ratings = df.groupby('City')['Aggregate rating'].mean()
print(City_ratings)

# convert the dataframe to a string and print it
print(df.to_string())

City
Abu Dhabi                 4.300000
Agra                      3.965000
Ahmedabad                 4.161905
Albany                    3.555000
Allahabad                 3.395000
Amritsar                  3.685714
Ankara                    4.305000
Armidale                  3.500000
Athens                    4.200000
Auckland                  4.275000
Augusta                   4.130000
Aurangabad                3.375000
Balingup                  3.200000
Bandung                   4.200000
Bangalore                 4.375000
Beechworth                4.600000
Bhopal                    3.950000
Bhubaneshwar              3.980952
Birmingham                3.680000
Bogor                     3.850000
Boise                     4.260000
Bras�_lia                 3.495000
Cape Town                 4.110000
Cedar Rapids/Iowa City    4.165000
Chandigarh                4.050000
Chatham-Kent              3.700000
Chennai                   4.315000
Clatskanie                4.300000
Cochrane                  3.100000
Coimbatore                4.135000
Colombo                   3.870000
Columbus                  4.030000
Consort                   3.000000
Dalton                    4.110000
Davenport                 3.715000
Dehradun                  4.050000
Des Moines                4.235000
Dicky Beach               3.600000
Doha                      4.060000
Dubai                     4.370000
Dubuque                   3.535000
East Ballina              4.100000
Edinburgh                 4.090000
Faridabad                 1.866932
Fernley                   3.700000
Flaxton                   3.500000
Forrest                   3.700000
Gainesville               4.035000
Ghaziabad                 2.852000
Goa                       4.245000
Gurgaon                   2.651431
Guwahati                  4.190476
Hepburn Springs           3.800000
Huskisson                 4.100000
Hyderabad                 4.344444
Indore                    3.970000
Inner City                4.900000
Inverloch                 3.700000
Jaipur                    4.130000
Jakarta                   4.356250
Johannesburg              4.200000
Kanpur                    3.815000
Kochi                     4.080000
Kolkata                   4.255000
Lakes Entrance            3.800000
Lakeview                  3.600000
Lincoln                   4.500000
London                    4.535000
Lorn                      3.600000
Lucknow                   4.195238
Ludhiana                  3.980000
Macedon                   3.500000
Macon                     4.115000
Makati City               4.650000
Manchester                4.045000
Mandaluyong City          4.625000
Mangalore                 3.745000
Mayfield                  2.900000
Mc Millan                 2.400000
Middleton Beach           3.800000
Miller                    3.400000
Mohali                    4.300000
Monroe                    3.600000
Montville                 2.400000
Mumbai                    4.085000
Mysore                    3.695000
Nagpur                    3.965000
Nashik                    3.520000
New Delhi                 2.438845
Noida                     2.036204
Ojo Caliente              3.600000
Orlando                   4.475000
Palm Cove                 4.400000
Panchkula                 4.200000
Pasay City                4.366667
Pasig City                4.633333
Patna                     3.455000
Paynesville               2.600000
Penola                    3.400000
Pensacola                 4.200000
Phillip Island            3.700000
Pocatello                 3.485000
Potrero                   3.300000
Pretoria                  4.190000
Princeton                 4.000000
Puducherry                3.730000
Pune                      4.220000
Quezon City               4.800000
Ranchi                    3.455000
Randburg                  4.300000
Rest of Hawaii            4.410000
Rio de Janeiro            4.265000
San Juan City             4.250000
Sandton                   4.300000
Santa Rosa                3.800000
Savannah                  4.155000
Secunderabad              4.500000
Sharjah                   4.030000
Singapore                 3.575000
Sioux City                3.765000
Surat                     3.935000
S��o Paulo                3.530000
Tagaytay City             4.500000
Taguig City               4.525000
Tampa Bay                 4.410000
Tangerang                 4.300000
Tanunda                   4.400000
Trentham East             4.100000
Vadodara                  4.025000
Valdosta                  3.715000
Varanasi                  3.510000
Vernonia                  4.300000
Victor Harbor             3.600000
Vineland Station          4.300000
Vizag                     4.005000
Waterloo                  3.650000
Weirton                   3.900000
Wellington City           4.250000
Winchester Bay            3.200000
Yorkton                   3.300000
��stanbul                 4.292857
Name: Aggregate rating, dtype: float64

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [22]:
highest_rating_city = City_ratings.idxmax()
print(highest_rating_city)

Inner City

# Based on our results:

1. The highest number of restaurants are in = New Delhi

2.The average rating for restaurants in each city are:

City
Abu Dhabi                 4.300000
Agra                      3.965000
Ahmedabad                 4.161905
Albany                    3.555000
Allahabad                 3.395000
Amritsar                  3.685714
Ankara                    4.305000
Armidale                  3.500000
Athens                    4.200000
Auckland                  4.275000
Augusta                   4.130000
Aurangabad                3.375000
Balingup                  3.200000
Bandung                   4.200000
Bangalore                 4.375000
Beechworth                4.600000
Bhopal                    3.950000
Bhubaneshwar              3.980952
Birmingham                3.680000
Bogor                     3.850000
Boise                     4.260000
Braslia                   3.495000
Cape Town                 4.110000
Cedar Rapids/Iowa City    4.165000
Chandigarh                4.050000
Chatham-Kent              3.700000
Chennai                   4.315000
Clatskanie                4.300000
Cochrane                  3.100000
Coimbatore                4.135000
Colombo                   3.870000
Columbus                  4.030000
Consort                   3.000000
Dalton                    4.110000
Davenport                 3.715000
Dehradun                  4.050000
Des Moines                4.235000
Dicky Beach               3.600000
Doha                      4.060000
Dubai                     4.370000
Dubuque                   3.535000
East Ballina              4.100000
Edinburgh                 4.090000
Faridabad                 1.866932
Fernley                   3.700000
Flaxton                   3.500000
Forrest                   3.700000
Gainesville               4.035000
Ghaziabad                 2.852000
Goa                       4.245000
Gurgaon                   2.651431
Guwahati                  4.190476
Hepburn Springs           3.800000
Huskisson                 4.100000
Hyderabad                 4.344444
Indore                    3.970000
Inner City                4.900000
Inverloch                 3.700000
Jaipur                    4.130000
Jakarta                   4.356250
Johannesburg              4.200000
Kanpur                    3.815000
Kochi                     4.080000
Kolkata                   4.255000
Lakes Entrance            3.800000
Lakeview                  3.600000
Lincoln                   4.500000
London                    4.535000
Lorn                      3.600000
Lucknow                   4.195238
Ludhiana                  3.980000
Macedon                   3.500000
Macon                     4.115000
Makati City               4.650000
Manchester                4.045000
Mandaluyong City          4.625000
Mangalore                 3.745000
Mayfield                  2.900000
Mc Millan                 2.400000
Middleton Beach           3.800000
Miller                    3.400000
Mohali                    4.300000
Monroe                    3.600000
Montville                 2.400000
Mumbai                    4.085000
Mysore                    3.695000
Nagpur                    3.965000
Nashik                    3.520000
New Delhi                 2.438845
Noida                     2.036204
Ojo Caliente              3.600000
Orlando                   4.475000
Palm Cove                 4.400000
Panchkula                 4.200000
Pasay City                4.366667
Pasig City                4.633333
Patna                     3.455000
Paynesville               2.600000
Penola                    3.400000
Pensacola                 4.200000
Phillip Island            3.700000
Pocatello                 3.485000
Potrero                   3.300000
Pretoria                  4.190000
Princeton                 4.000000
Puducherry                3.730000
Pune                      4.220000
Quezon City               4.800000
Ranchi                    3.455000
Randburg                  4.300000
Rest of Hawaii            4.410000
Rio de Janeiro            4.265000
San Juan City             4.250000
Sandton                   4.300000
Santa Rosa                3.800000
Savannah                  4.155000
Secunderabad              4.500000
Sharjah                   4.030000
Singapore                 3.575000
Sioux City                3.765000
Surat                     3.935000
So Paulo                  3.530000
Tagaytay City             4.500000
Taguig City               4.525000
Tampa Bay                 4.410000
Tangerang                 4.300000
Tanunda                   4.400000
Trentham East             4.100000
Vadodara                  4.025000
Valdosta                  3.715000
Varanasi                  3.510000
Vernonia                  4.300000
Victor Harbor             3.600000
Vineland Station          4.300000
Vizag                     4.005000
Waterloo                  3.650000
Weirton                   3.900000
Wellington City           4.250000
Winchester Bay            3.200000
Yorkton                   3.300000
Istanbul                  4.292857

In [26]:
"""
2.The average rating for restaurants in each city are:

City
Abu Dhabi                 4.300000
Agra                      3.965000
Ahmedabad                 4.161905
Albany                    3.555000
Allahabad                 3.395000
Amritsar                  3.685714
Ankara                    4.305000
Armidale                  3.500000
Athens                    4.200000
Auckland                  4.275000
Augusta                   4.130000
Aurangabad                3.375000
Balingup                  3.200000
Bandung                   4.200000
Bangalore                 4.375000
Beechworth                4.600000
Bhopal                    3.950000
Bhubaneshwar              3.980952
Birmingham                3.680000
Bogor                     3.850000
Boise                     4.260000
Braslia                   3.495000
Cape Town                 4.110000
Cedar Rapids/Iowa City    4.165000
Chandigarh                4.050000
Chatham-Kent              3.700000
Chennai                   4.315000
Clatskanie                4.300000
Cochrane                  3.100000
Coimbatore                4.135000
Colombo                   3.870000
Columbus                  4.030000
Consort                   3.000000
Dalton                    4.110000
Davenport                 3.715000
Dehradun                  4.050000
Des Moines                4.235000
Dicky Beach               3.600000
Doha                      4.060000
Dubai                     4.370000
Dubuque                   3.535000
East Ballina              4.100000
Edinburgh                 4.090000
Faridabad                 1.866932
Fernley                   3.700000
Flaxton                   3.500000
Forrest                   3.700000
Gainesville               4.035000
Ghaziabad                 2.852000
Goa                       4.245000
Gurgaon                   2.651431
Guwahati                  4.190476
Hepburn Springs           3.800000
Huskisson                 4.100000
Hyderabad                 4.344444
Indore                    3.970000
Inner City                4.900000
Inverloch                 3.700000
Jaipur                    4.130000
Jakarta                   4.356250
Johannesburg              4.200000
Kanpur                    3.815000
Kochi                     4.080000
Kolkata                   4.255000
Lakes Entrance            3.800000
Lakeview                  3.600000
Lincoln                   4.500000
London                    4.535000
Lorn                      3.600000
Lucknow                   4.195238
Ludhiana                  3.980000
Macedon                   3.500000
Macon                     4.115000
Makati City               4.650000
Manchester                4.045000
Mandaluyong City          4.625000
Mangalore                 3.745000
Mayfield                  2.900000
Mc Millan                 2.400000
Middleton Beach           3.800000
Miller                    3.400000
Mohali                    4.300000
Monroe                    3.600000
Montville                 2.400000
Mumbai                    4.085000
Mysore                    3.695000
Nagpur                    3.965000
Nashik                    3.520000
New Delhi                 2.438845
Noida                     2.036204
Ojo Caliente              3.600000
Orlando                   4.475000
Palm Cove                 4.400000
Panchkula                 4.200000
Pasay City                4.366667
Pasig City                4.633333
Patna                     3.455000
Paynesville               2.600000
Penola                    3.400000
Pensacola                 4.200000
Phillip Island            3.700000
Pocatello                 3.485000
Potrero                   3.300000
Pretoria                  4.190000
Princeton                 4.000000
Puducherry                3.730000
Pune                      4.220000
Quezon City               4.800000
Ranchi                    3.455000
Randburg                  4.300000
Rest of Hawaii            4.410000
Rio de Janeiro            4.265000
San Juan City             4.250000
Sandton                   4.300000
Santa Rosa                3.800000
Savannah                  4.155000
Secunderabad              4.500000
Sharjah                   4.030000
Singapore                 3.575000
Sioux City                3.765000
Surat                     3.935000
So Paulo                  3.530000
Tagaytay City             4.500000
Taguig City               4.525000
Tampa Bay                 4.410000
Tangerang                 4.300000
Tanunda                   4.400000
Trentham East             4.100000
Vadodara                  4.025000
Valdosta                  3.715000
Varanasi                  3.510000
Vernonia                  4.300000
Victor Harbor             3.600000
Vineland Station          4.300000
Vizag                     4.005000
Waterloo                  3.650000
Weirton                   3.900000
Wellington City           4.250000
Winchester Bay            3.200000
Yorkton                   3.300000
Istanbul                  4.292857



"""

'\n2.The average rating for restaurants in each city are:\n\nCity\nAbu Dhabi                 4.300000\nAgra                      3.965000\nAhmedabad                 4.161905\nAlbany                    3.555000\nAllahabad                 3.395000\nAmritsar                  3.685714\nAnkara                    4.305000\nArmidale                  3.500000\nAthens                    4.200000\nAuckland                  4.275000\nAugusta                   4.130000\nAurangabad                3.375000\nBalingup                  3.200000\nBandung                   4.200000\nBangalore                 4.375000\nBeechworth                4.600000\nBhopal                    3.950000\nBhubaneshwar              3.980952\nBirmingham                3.680000\nBogor                     3.850000\nBoise                     4.260000\nBraslia                   3.495000\nCape Town                 4.110000\nCedar Rapids/Iowa City    4.165000\nChandigarh                4.050000\nChatham-Kent              3.700000\nChennai                   4.315000\nClatskanie                4.300000\nCochrane                  3.100000\nCoimbatore                4.135000\nColombo                   3.870000\nColumbus                  4.030000\nConsort                   3.000000\nDalton                    4.110000\nDavenport                 3.715000\nDehradun                  4.050000\nDes Moines                4.235000\nDicky Beach               3.600000\nDoha                      4.060000\nDubai                     4.370000\nDubuque                   3.535000\nEast Ballina              4.100000\nEdinburgh                 4.090000\nFaridabad                 1.866932\nFernley                   3.700000\nFlaxton                   3.500000\nForrest                   3.700000\nGainesville               4.035000\nGhaziabad                 2.852000\nGoa                       4.245000\nGurgaon                   2.651431\nGuwahati                  4.190476\nHepburn Springs           3.800000\nHuskisson                 4.100000\nHyderabad                 4.344444\nIndore                    3.970000\nInner City                4.900000\nInverloch                 3.700000\nJaipur                    4.130000\nJakarta                   4.356250\nJohannesburg              4.200000\nKanpur                    3.815000\nKochi                     4.080000\nKolkata                   4.255000\nLakes Entrance            3.800000\nLakeview                  3.600000\nLincoln                   4.500000\nLondon                    4.535000\nLorn                      3.600000\nLucknow                   4.195238\nLudhiana                  3.980000\nMacedon                   3.500000\nMacon                     4.115000\nMakati City               4.650000\nManchester                4.045000\nMandaluyong City          4.625000\nMangalore                 3.745000\nMayfield                  2.900000\nMc Millan                 2.400000\nMiddleton Beach           3.800000\nMiller                    3.400000\nMohali                    4.300000\nMonroe                    3.600000\nMontville                 2.400000\nMumbai                    4.085000\nMysore                    3.695000\nNagpur                    3.965000\nNashik                    3.520000\nNew Delhi                 2.438845\nNoida                     2.036204\nOjo Caliente              3.600000\nOrlando                   4.475000\nPalm Cove                 4.400000\nPanchkula                 4.200000\nPasay City                4.366667\nPasig City                4.633333\nPatna                     3.455000\nPaynesville               2.600000\nPenola                    3.400000\nPensacola                 4.200000\nPhillip Island            3.700000\nPocatello                 3.485000\nPotrero                   3.300000\nPretoria                  4.190000\nPrinceton                 4.000000\nPuducherry                3.730000\nPune                      4.220000\nQuezon City               4.800000\nRanchi                    3.455000\nRandburg                  4.300000\nRest of Hawaii            4.410000\nRio de Janeiro            4.265000\nSan Juan City             4.250000\nSandton                   4.300000\nSanta Rosa                3.800000\nSavannah                  4.155000\nSecunderabad              4.500000\nSharjah                   4.030000\nSingapore                 3.575000\nSioux City                3.765000\nSurat                     3.935000\nSo Paulo                  3.530000\nTagaytay City             4.500000\nTaguig City               4.525000\nTampa Bay                 4.410000\nTangerang                 4.300000\nTanunda                   4.400000\nTrentham East             4.100000\nVadodara                  4.025000\nValdosta                  3.715000\nVaranasi                  3.510000\nVernonia                  4.300000\nVictor Harbor             3.600000\nVineland Station          4.300000\nVizag                     4.005000\nWaterloo                  3.650000\nWeirton                   3.900000\nWellington City           4.250000\nWinchester Bay            3.200000\nYorkton                   3.300000\nIstanbul                  4.292857\n\n\n\n'

# -->The highest average rating of city is Inner City(4.90
)